---
- name: Git checkout with key
  ansible.builtin.git:
    repo: "{{ git_repo_url }}"
    dest: "{{ git_repo_destination }}/{{ git_repo_name }}"
    key_file: "{{ git_key_file }}"
    version: development
    accept_hostkey: true
  when: git_key_file is defined
  register: result

- name: Git checkout without key (unauthenticated)
  ansible.builtin.git:
    repo: "{{ git_repo_url }}"
    dest: "{{ git_repo_destination }}/{{ git_repo_name }}"
    accept_hostkey: true
  when: git_key_file is not defined
  register: result
