---
- name: Run bat playbook
  hosts: localhost
  tasks:
    - name: Set facts part 1
      ansible.builtin.set_fact:
        this_package_name: lazygit
        this_git_repo_name: pub_config

    - name: Set facts part 2
      ansible.builtin.set_fact:
        this_git_repo_subfolder_name: '{{ this_package_name }}'
        this_git_repo_destination: '{{ global.git_repo_destination }}/{{ this_git_repo_name }}'

    - name: Install {{ this_package_name }}
      ansible.builtin.include_tasks: common_tasks/package_installer.yaml
      vars:
        package_name: '{{ this_package_name }}'

    - name: Clone configuration
      ansible.builtin.include_tasks: common_tasks/git_installer.yaml
      vars:
        git_repo_url: git@github.com:susiteemu/pub_config.git
        git_repo_name: '{{ this_git_repo_name }}'
        git_repo_destination: '{{ global.git_repo_destination }}'

    - name: Create configuration folder
      ansible.builtin.file:
        path: '{{ global.workstation_configuration }}/{{ this_git_repo_subfolder_name }}'
        state: directory
        mode: u=rwx,g=r,o=r

    - name: Create a symbolic link from cloned configuration to workstation configuration
      ansible.builtin.include_tasks: common_tasks/symlink_creator.yaml
      vars:
        src: '{{ this_git_repo_destination }}/{{ this_git_repo_subfolder_name }}/config.yml'
        dest: '{{ global.workstation_configuration }}/{{ this_package_name }}/config.yml'

    - name: Notice
      ansible.builtin.debug:
        msg: Remember to run fish shell configuration setup tasks to enable required environment settings
